# -*- coding: utf-8 -*-
"""9/2 컴퓨터 프로그래밍 1주차 실습

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G27pv8rlx8cTcV__kN5jQwoIehK8mc18
"""

print("Hello World")
#print("Bye World")